# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148KuiWFSiDi3KdETlBLx95NFInltlmQz
"""

import pandas as pd
import datetime as dt

valor = float(input('Informe o valor do processo: '))
dataEntrada = input("Informe a data de chegada do processo: ")
dataSaida =  input("Informe a data de retirada do processo: ")

#convertendo para date time
dataEntrada = dt.datetime.strptime(dataEntrada, '%d/%m/%Y')
dataSaida = dt.datetime.strptime(dataSaida, '%d/%m/%Y')

DiasArmazenados = dataSaida - dataEntrada
DiasArmazenados = DiasArmazenados.days
#traformando os dias armazenados em int
Armazenagem = int(DiasArmazenados) +1
print(f"O processo ficou armazenado {Armazenagem} dias")



periodo1 = list(range(1,9))
periodo2 = list(range(9,21))
periodo3 = list(range(22,1000))
periodo1pct = 0.00220
periodo2pct= 0.00200
periodo3pct = 0.00350


if Armazenagem in periodo1:
  resultado = (periodo1pct * valor)+335
  if resultado <= 575:
    print(f"O valor da Armazengem é de R$575,00 e o processo se encontra no primeiro periodo");
  else:
      print(f"O valor da Armazengem é de R${resultado} e o processo se encontra no primeiro periodo")
if Armazenagem in periodo2:
  resultado =(periodo1pct * valor) + (valor * periodo2pct * (Armazenagem -8))+335
  print(f"O valor da armazenagem é de R${resultado} e o processo se encontra no segundo periodo tome cuidado com a Demurrage");
if Armazenagem in periodo3:
  resultado =(periodo1pct * valor) + (periodo2pct *valor * 12) + (periodo3pct * valor* (Armazenagem - 20))+335
  print(f"O valor da armazenagem é de R${resultado} e o processo se encontra no terceir periodo tome cuidado com a Demurrage");